### ISSUE TITLE
Toggle changing window scroll position

### ISSUE THREAD

**Issue by baroca** [sdrichter/QualityHighlighter#4] opened 2016-01-13 05:36 UTC
When the list of entries is ordered alphabetically toggling the plugin will change the window position previously set.

To replicate, a large enough list of entries is necessary in order to the scroll bar be displayed.

Great plugin by the way!

Cheers

**Comment by sdrichter** [comment] 2016-03-20 12:36
Hey there. Thanks for reporting the issue. I am unable to reproduce it on version 2.31 of KeePass2 on Ubuntu. What version of KeePass2 are you using? What platform are you running on?

**Comment by sdrichter** [comment] 2017-01-14 13:56
Reproduced. Working on a fix.

**Comment by sdrichter** [comment] 2017-01-14 14:20
This has been fixed on latest master commit.

**Closed as completed by sdrichter** 2017-01-14 14:20 UTC
